apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
  labels:
    app: story-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: shykhovmyron/story-app:latest
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: STORY_FOLDER
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: data-pvc
      restartPolicy: Always
  selector:
    matchLabels:
      app: story
