apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  volumeName: data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standart
  resources:
    requests:
      storage: 1Gi